version: "3"
services:

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - mern-network

  server:
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - mern-network

  client:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge